// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reva.Infrastructure.Persistence;

#nullable disable

namespace Reva.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RevaDbContext))]
    partial class RevaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Reva.Infrastructure.Persistence.AppSettingsRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccentColor")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<double>("ConfidenceLowMax")
                        .HasColumnType("REAL");

                    b.Property<double>("ConfidenceMediumMax")
                        .HasColumnType("REAL");

                    b.Property<Guid?>("DefaultTemplateId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<double>("ReconciliationTolerance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.01);

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseLlmAssist")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("Reva.Infrastructure.Persistence.DocumentFieldRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<Guid>("DocumentRecordId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCorrected")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DocumentRecordId");

                    b.ToTable("DocumentFieldRecord");
                });

            modelBuilder.Entity("Reva.Infrastructure.Persistence.DocumentIssueRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<string>("Detected")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DocumentRecordId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Expected")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldName")
                        .HasMaxLength(96)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DocumentRecordId");

                    b.ToTable("DocumentIssueRecord");
                });

            modelBuilder.Entity("Reva.Infrastructure.Persistence.DocumentPageRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DocumentRecordId")
                        .HasColumnType("TEXT");

                    b.Property<double>("Height")
                        .HasColumnType("REAL");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("Page")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rotation")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Width")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("DocumentRecordId");

                    b.ToTable("DocumentPages");
                });

            modelBuilder.Entity("Reva.Infrastructure.Persistence.DocumentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParsedJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParsedMarkdown")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParserProfile")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha256Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Sha256Hash")
                        .IsUnique();

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("Reva.Infrastructure.Persistence.DocumentSchemaMappingRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CanonicalField")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("TEXT");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<Guid>("DocumentRecordId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCorrected")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLearned")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedSourceHeader")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedValue")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceHeader")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DocumentRecordId");

                    b.ToTable("DocumentSchemaMappingRecord");
                });

            modelBuilder.Entity("Reva.Infrastructure.Persistence.DocumentSourceSpanRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BlockId")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ColumnIndex")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DocumentRecordId")
                        .HasColumnType("TEXT");

                    b.Property<double>("Height")
                        .HasColumnType("REAL");

                    b.Property<double?>("OcrConfidence")
                        .HasColumnType("REAL");

                    b.Property<int>("Page")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PageHeight")
                        .HasColumnType("REAL");

                    b.Property<double>("PageWidth")
                        .HasColumnType("REAL");

                    b.Property<string>("PolygonJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rotation")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RowIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpanId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("TableId")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<double>("Width")
                        .HasColumnType("REAL");

                    b.Property<double>("X")
                        .HasColumnType("REAL");

                    b.Property<double>("Y")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("DocumentRecordId");

                    b.ToTable("DocumentSourceSpans");
                });

            modelBuilder.Entity("Reva.Infrastructure.Persistence.DocumentTableRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DocumentRecordId")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeadersJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("TEXT");

                    b.Property<string>("RowsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DocumentRecordId");

                    b.ToTable("DocumentTableRecord");
                });

            modelBuilder.Entity("Reva.Infrastructure.Persistence.ExportTemplateRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ColumnsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ExportTemplates");
                });

            modelBuilder.Entity("Reva.Infrastructure.Persistence.LearnedSchemaMappingRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CanonicalField")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedSourceHeader")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceHeader")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UseCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SenderKey", "NormalizedSourceHeader")
                        .IsUnique();

                    b.ToTable("LearnedSchemaMappings");
                });

            modelBuilder.Entity("Reva.Infrastructure.Persistence.ReviewEventRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DocumentRecordId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reviewer")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DocumentRecordId");

                    b.ToTable("ReviewEventRecord");
                });

            modelBuilder.Entity("Reva.Infrastructure.Persistence.DocumentFieldRecord", b =>
                {
                    b.HasOne("Reva.Infrastructure.Persistence.DocumentRecord", null)
                        .WithMany("Fields")
                        .HasForeignKey("DocumentRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Reva.Infrastructure.Persistence.DocumentIssueRecord", b =>
                {
                    b.HasOne("Reva.Infrastructure.Persistence.DocumentRecord", null)
                        .WithMany("Exceptions")
                        .HasForeignKey("DocumentRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Reva.Infrastructure.Persistence.DocumentPageRecord", b =>
                {
                    b.HasOne("Reva.Infrastructure.Persistence.DocumentRecord", null)
                        .WithMany("Pages")
                        .HasForeignKey("DocumentRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Reva.Infrastructure.Persistence.DocumentSchemaMappingRecord", b =>
                {
                    b.HasOne("Reva.Infrastructure.Persistence.DocumentRecord", null)
                        .WithMany("SchemaMappings")
                        .HasForeignKey("DocumentRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Reva.Infrastructure.Persistence.DocumentSourceSpanRecord", b =>
                {
                    b.HasOne("Reva.Infrastructure.Persistence.DocumentRecord", null)
                        .WithMany("SourceSpans")
                        .HasForeignKey("DocumentRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Reva.Infrastructure.Persistence.DocumentTableRecord", b =>
                {
                    b.HasOne("Reva.Infrastructure.Persistence.DocumentRecord", null)
                        .WithMany("Tables")
                        .HasForeignKey("DocumentRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Reva.Infrastructure.Persistence.ReviewEventRecord", b =>
                {
                    b.HasOne("Reva.Infrastructure.Persistence.DocumentRecord", null)
                        .WithMany("ReviewEvents")
                        .HasForeignKey("DocumentRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Reva.Infrastructure.Persistence.DocumentRecord", b =>
                {
                    b.Navigation("Exceptions");

                    b.Navigation("Fields");

                    b.Navigation("Pages");

                    b.Navigation("ReviewEvents");

                    b.Navigation("SchemaMappings");

                    b.Navigation("SourceSpans");

                    b.Navigation("Tables");
                });
#pragma warning restore 612, 618
        }
    }
}
